// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBPyeC6_r3XkFddsbHROHnqan7rOmGDS4',
    appId: '1:148495044116:web:087026a7b72edf0bdb6101',
    messagingSenderId: '148495044116',
    projectId: 'smarttaskapp-c29df',
    authDomain: 'smarttaskapp-c29df.firebaseapp.com',
    storageBucket: 'smarttaskapp-c29df.firebasestorage.app',
    measurementId: 'G-371VYP16FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvhAP5Iq7YLG-bYVZ32nvMG-OmTf36m_Y',
    appId: '1:148495044116:android:3a95000bec586823db6101',
    messagingSenderId: '148495044116',
    projectId: 'smarttaskapp-c29df',
    storageBucket: 'smarttaskapp-c29df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbpSCBX5_1sHljc4bY2RIvi9fTxgCJYbU',
    appId: '1:148495044116:ios:c451c249b0f07433db6101',
    messagingSenderId: '148495044116',
    projectId: 'smarttaskapp-c29df',
    storageBucket: 'smarttaskapp-c29df.firebasestorage.app',
    androidClientId: '148495044116-mnun6t4b9ook7jta3q61ivqmr5gra5ac.apps.googleusercontent.com',
    iosClientId: '148495044116-iiaea9k4klmdhepit970m9nap8dvm1n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbpSCBX5_1sHljc4bY2RIvi9fTxgCJYbU',
    appId: '1:148495044116:ios:c451c249b0f07433db6101',
    messagingSenderId: '148495044116',
    projectId: 'smarttaskapp-c29df',
    storageBucket: 'smarttaskapp-c29df.firebasestorage.app',
    androidClientId: '148495044116-mnun6t4b9ook7jta3q61ivqmr5gra5ac.apps.googleusercontent.com',
    iosClientId: '148495044116-iiaea9k4klmdhepit970m9nap8dvm1n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTaskApp',
  );
}
